### PR TITLE
Get and load Google Analytics ID from URL parameter

### PR DESCRIPTION
**Pull request by gocemitevski**
This PR makes the Google Analytics ID dynamically set from the `id` URL parameter.

### CODE REVIEW

**Comment by pwalsh** [comment]
@gocemitevski 

The page needs to have the `googleAnalyticsCode` set, with a value, whether cookies are accepted or not.

When the user consents, the consent script uses this value because it knows which variable to expect to already be on the page.

There is no need for a URL param - the value is already on the page in a variable.

**Comment by gocemitevski** [comment]
@pwalsh we have only one set of scripts that handle Cookie Consent, so if we want to use it via an `<iframe>` I don't see how we could pass the environment variable to CC in a different way.

Also, the `<iframe>` we are about to use in WordPress needs to have a connection to `googleAnalyticsCode` and it doesn't if we don't pass the value through a URL parameter.

Now I don't think I understand what you want. Please provide more details.

**Comment by pwalsh** [comment]
@gocemitevski can you explain how an iframe *will* work? How your solution sets the analytics script on the parent, and not in the iframe itself?

When I reviewed https://github.com/okfn/a/blob/master/a/html/oki/consent/index.html I was not thinking about it being an iframe (I was assuming this is a demo of how you will include the solution on any page).

So, in order that I can understand your solution, can you outline the steps where, on consent, the GS script is loaded on the page the user requested.

**Comment by gocemitevski** [comment]
@pwalsh the idea is to load https://a.okfn.org/html/oki/consent/ through an `<iframe>` wherever needed and to somehow set the value of `googleAnalyticsCode` in the `<iframe>` - exactly why I suggest we use URL parameters. For the WordPress websites, we would read that value from the environment variables, so it will only be set once per site.

Once the googleAnalyticsCode is set, Cookie Consent can load the required content upon user action.

> When I reviewed https://github.com/okfn/a/blob/master/a/html/oki/consent/index.html I was not thinking about it being an iframe (I was assuming this is a demo of how you will include the solution on any page).

Correct. It is supposed to be used that way, but we still need to somehow load the code per page, per site, which complicates things a bit. If the intention is to have this code cloned somewhere within the websites and configure it manually for each website, I guess we don't need the `<iframe>`. We would most certainly need a custom WP plugin with the same code, for loading Cookie Consent across the blogfarm.

So, in the end, my intention is to avoid doing manual work and automate things as much as possible.

**Comment by pwalsh** [comment]
@gocemitevski so setting the code in the iframe does not have the desired outcome - we need the code set on the page the user is loading, otherwise we are just collecting analytics for the URL of the iframe page.

The code would have to be loaded in the page itself. if right now, the easiest way to do that is to clone/copy this code to get a test running on WP, please do.

**Comment by gocemitevski** [comment]
@pwalsh please see if this makes sense: https://developers.google.com/analytics/devguides/collection/analyticsjs/cross-domain#iframes

For WordPress, I will publish the plugin code shortly and activate it on OKI websites.

**Pull request closed without merging**
